### PR TITLE
CI test on hardware

### PR DESCRIPTION
**Pull request by IgorBagnucki**

### CODE REVIEW

**Comment by macpijan** [comment]
@IgorBagnucki Please resolve conflicts

**Comment by IgorBagnucki** [comment]
@macpijan I don't see any conflicts and can merge `hw_test` into `talos_2_support_payload` locally with no problem. Should I merge it if You have some kind of issue?

**Comment by IgorBagnucki** [comment]
@macpijan The conflicts are resolved. Only waiting for over-night HW test now.

**Comment by IgorBagnucki** [comment]
@macpijan Over-night test passed, so I guess it's ready to merge.

**Pull request merged**
