### PR TITLE
VPD parsing

### PR DESCRIPTION
**Pull request by SergiiDmytruk**
[IOP-111]

Don't know if it makes sense to optimize keywords lookup by creating an index, but there are multiple searches.

Can drop size checks that present and just `die()` if keyword is not 255 bytes in length, Hostboot just asserts for size.

Also we make assumptions about data, so maybe should verify both layout and data versions for keywords.

### CODE REVIEW

**Comment by macpijan** [comment]
@SergiiDmytruk Please remove the WIP status if you believe it is ready for review. First note is that you should work on the commit messages (epsecially get rid of the WIP commits). Most likely squashing in less commits would be a good fit here.

**Comment by SergiiDmytruk** [comment]
@macpijan, better commits are [here](https://github.com/SergiiDmytruk/coreboot/commits/vpd-on-pnor). I need code from `pnor` branch (PR #19) but data itself is from `istep_13_11` branch, where these changes are needed. Because of this I'm not sure what should be my base and target branches.

**Comment by macpijan** [comment]
@SergiiDmytruk Understood. Thanks for the link. I will leave @krystian-hebel to how to handle this (target branch).

**Comment by krystian-hebel** [comment]
Yes, the other branch seems better, and it will be better to merge to `pnor`. @SergiiDmytruk please make a new PR from that code and I'll give a more thorough review there, and I think this one can be closed?

**Comment by SergiiDmytruk** [comment]
@krystian-hebel, I just force-pushed and changed base on this one. There were no review comments anyway. I'll add code to extract missing attributes and will unmark the PR as a draft.

**Review by krystian-hebel — APPROVED** [review]
I have not checked all individual attributes, but given that it is able to perform DRAM training I assume they are good (or at least close enough).

This made an error in my code visible, I'll fix it in a separate commit, along with some additional checks against re-using CBFS cache, otherwise LGTM.

**Pull request merged**
