### PR TITLE
get CBFS from PNOR

### PR DESCRIPTION
**Pull request by krystian-hebel**

### CODE REVIEW

**Comment by miczyg1** [comment]
@krystian-hebel can we get this PR cleaned up for merging?

**Comment by macpijan** [comment]
@miczyg1 Please take a look on that

**Comment by krystian-hebel** [comment]
@miczyg1 ping

**Comment by krystian-hebel** [comment]
I just found out that there are better functions for mmaping, will have to update this PR.

**Comment by macpijan** [comment]
@krystian-hebel Is this updated with those new functions already?

**Comment by krystian-hebel** [comment]
Yes, it is, forgot to submit a comment.

**Comment by macpijan** [comment]
@miczyg1 This should be ready to review/merge then

**Pull request merged**
